name: Deploy Lambda (x86_64)

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Lambda package (x86_64)
        run: |
          pip install -r requirements.txt -t .
          zip -r lambda_function.zip .

      - name: Configure AWS credentials for DEV
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-2

      - name: Configure AWS credentials for PROD
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-2

      - name: Deploy Lambda function (DEV)
        if: github.ref == 'refs/heads/develop'
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:211125575240:function:AmazonMassiveMigration \
            --zip-file fileb://lambda_function.zip

      - name: Deploy Lambda function (PROD)
        if: github.ref == 'refs/heads/master'
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:975049950271:function:AmazonMassiveMigration \
            --zip-file fileb://lambda_function.zip